connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, extending-connect-adapters/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 3.42.1.0</em></summary>
</details>
</details>
<details>
<summary>Changed 4 files: </summary>
</details>
<hr>
[:octocat: Repo](https://github.com/technote-space/create-pr-action) | [:memo: Issues](https://github.com/technote-space/create-pr-action/issues) | [:department_store: …
=> Auto-upgrade to 3.42.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 4.48.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 4.48.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 3.43.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 3.43.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.0.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.0.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.1.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.1.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.4.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.4.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
</details>
<details>
<summary>Changed file: </summary>
</details>
<hr>
[:octocat: Repo](https://github.com/technote-space/create-pr-action) | [:memo: Issues](https://github.com/technote-space/create-pr-action/issues) | [:department_store: Marketplace](https://github.com/marketplace/actions/create-pr-action)
=> Auto-upgrade to 5.6.4.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.1.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.1.5.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.7.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.7.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.7.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.7.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.7.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.7.3.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.7.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.7.4.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.7.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.7.5.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.2.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.2.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.8.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.8.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.8.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.8.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.8.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.8.3.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.8.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.8.4.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.8.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.8.5.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.8.6.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.8.6.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.2.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.2.5.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.9.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.9.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.10.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.10.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.10.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.10.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.10.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.10.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.10.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.10.3.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.10.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.10.4.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.6.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.6.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.10.6.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.10.6.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.10.7.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.10.7.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.11.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.11.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.6.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.6.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.11.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.11.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.12.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.12.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.6.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.6.3.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.6.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.6.5.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.12.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.12.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.12.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.12.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.12.2.1</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.12.2.1

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.13.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.13.0.1

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.13.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.6.8.2</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.6.8.2

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.6.10.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.6.10.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.6.11.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.6.11.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.13.4.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.13.5.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.6.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.13.6.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.6.14.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.6.14.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.6.15.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.6.15.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.8.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.13.8.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.13.9.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.13.9.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.14.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.14.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.14.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.14.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.14.4.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.14.4.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.14.5.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.14.5.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.15.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.15.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.16.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.16.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.16.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.16.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.17.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.17.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.18.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.18.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.18.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.18.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.19.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.19.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.20.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.20.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.21.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.21.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.21.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.21.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.21.2.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.21.2.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.16.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.16.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.16.0.2</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.16.0.2

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.24.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.24.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.24.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.24.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.17.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.17.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.25.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.25.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.18.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.18.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, developing-openai-plugins/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.26.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.26.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.26.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.26.1.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.27.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.27.0.0

connect-pattern/gradle.properties, custom-adapter-and-fake/gradle.properties, extending-connect-adapters/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-adapters/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.28.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.28.0.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.28.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.28.1.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.22.0.00</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.22.0.00

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.22.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.22.1.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.29.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.29.0.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.23.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.23.0.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.30.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.30.0.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.30.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.30.1.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.31.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.31.0.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.31.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.31.1.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.32.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.32.1.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.32.3.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.32.3.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.33.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.33.0.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.33.0.1</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.33.0.1

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k_connect.sh 5.25.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.25.1.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.33.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.33.1.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.34.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.34.0.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.34.1.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.34.1.0

connect-pattern/gradle.properties, custom-api-client-and-fake/gradle.properties, extending-connect-api-clients/gradle.properties, fakes-in-official-aws-sdk/gradle.properties, using-connect-api-clients/gradle.properties
<details>
<details>
```Shell
```
</details>
<details>
<summary><em>./upgrade_http4k.sh 5.35.0.0</em></summary>
</details>
</details>
<details>
</details>
<hr> …
=> Auto-upgrade to 5.35.0.0
